spring:
  config:
    activate:
      on-profile: qa

build:
  version: v40.0

accounts:
  version: ${build.version}
  msg: This is accounts microservice - QA GitHub 2
  contact-details:
    email: qa@email.com
    phone: +91 7782563629
  callSupport:
    -"1800-000-555"
    -"1800-000-666"
